# Generated by Django 5.2.4 on 2025-09-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_is_published_article_price_post_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
